// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Task struct {
	ID             uuid.UUID     `json:"id"`
	Title          string        `json:"title"`
	Description    string        `json:"description"`
	CreatedAt      time.Time     `json:"created_at"`
	CompletedAt    sql.NullTime  `json:"completed_at"`
	Duration       string        `json:"duration"`
	Category       string        `json:"category"`
	Tags           []string      `json:"tags"`
	ToggledAt      sql.NullInt64 `json:"toggled_at"`
	IsActive       bool          `json:"is_active"`
	IsCompleted    bool          `json:"is_completed"`
	UserID         uuid.UUID     `json:"user_id"`
	LastModifiedAt int64         `json:"last_modified_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	Email       string         `json:"email"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Categories  sql.NullString `json:"categories"`
	KeyCommands sql.NullString `json:"key_commands"`
	GoogleUid   sql.NullString `json:"google_uid"`
}
